# Generated by Django 5.0.3 on 2024-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='password',
        ),
        migrations.AddField(
            model_name='password',
            name='encrypted_password',
            field=models.BinaryField(null=True),
        ),
    ]
