# Generated by Django 5.0.3 on 2024-04-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0002_remove_password_password_password_encrypted_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='decrypted_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='encrypted_password',
            field=models.BinaryField(),
        ),
    ]
