# Generated by Django 5.0.3 on 2024-04-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0005_remove_password_decrypted_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='decrypted_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
